echo 'src/output/gemini-1.5-flash'
cat 'src/output/gemini-1.5-flash.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-1.5-flash_relink.md' > 'src/output/gemini-1.5-flash_relink.md' 2> 'src/output/gemini-1.5-flash_perc.txt'
echo 'src/output/learnlm-2.0-flash-experimental'
cat 'src/output/learnlm-2.0-flash-experimental.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/learnlm-2.0-flash-experimental_relink.md' > 'src/output/learnlm-2.0-flash-experimental_relink.md' 2> 'src/output/learnlm-2.0-flash-experimental_perc.txt'
echo 'src/output/gemini-2.0-flash-exp'
cat 'src/output/gemini-2.0-flash-exp.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.0-flash-exp_relink.md' > 'src/output/gemini-2.0-flash-exp_relink.md' 2> 'src/output/gemini-2.0-flash-exp_perc.txt'
echo 'src/output/gemini-2.0-flash-thinking-exp'
cat 'src/output/gemini-2.0-flash-thinking-exp.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.0-flash-thinking-exp_relink.md' > 'src/output/gemini-2.0-flash-thinking-exp_relink.md' 2> 'src/output/gemini-2.0-flash-thinking-exp_perc.txt'
echo 'src/output/gemini-2.0-flash-thinking-exp-1219'
cat 'src/output/gemini-2.0-flash-thinking-exp-1219.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.0-flash-thinking-exp-1219_relink.md' > 'src/output/gemini-2.0-flash-thinking-exp-1219_relink.md' 2> 'src/output/gemini-2.0-flash-thinking-exp-1219_perc.txt'
echo 'src/output/gemini-1.5-flash-latest'
cat 'src/output/gemini-1.5-flash-latest.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-1.5-flash-latest_relink.md' > 'src/output/gemini-1.5-flash-latest_relink.md' 2> 'src/output/gemini-1.5-flash-latest_perc.txt'
echo 'src/output/gemini-1.5-flash-8b-latest'
cat 'src/output/gemini-1.5-flash-8b-latest.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-1.5-flash-8b-latest_relink.md' > 'src/output/gemini-1.5-flash-8b-latest_relink.md' 2> 'src/output/gemini-1.5-flash-8b-latest_perc.txt'
echo 'src/output/gemini-2.0-flash-exp-image-generation'
cat 'src/output/gemini-2.0-flash-exp-image-generation.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.0-flash-exp-image-generation_relink.md' > 'src/output/gemini-2.0-flash-exp-image-generation_relink.md' 2> 'src/output/gemini-2.0-flash-exp-image-generation_perc.txt'
echo 'src/output/gemini-1.5-flash-8b-001'
cat 'src/output/gemini-1.5-flash-8b-001.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-1.5-flash-8b-001_relink.md' > 'src/output/gemini-1.5-flash-8b-001_relink.md' 2> 'src/output/gemini-1.5-flash-8b-001_perc.txt'
echo 'src/output/gemini-2.0-flash-thinking-exp-01-21'
cat 'src/output/gemini-2.0-flash-thinking-exp-01-21.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.0-flash-thinking-exp-01-21_relink.md' > 'src/output/gemini-2.0-flash-thinking-exp-01-21_relink.md' 2> 'src/output/gemini-2.0-flash-thinking-exp-01-21_perc.txt'
echo 'src/output/gemini-2.5-flash'
cat 'src/output/gemini-2.5-flash.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.5-flash_relink.md' > 'src/output/gemini-2.5-flash_relink.md' 2> 'src/output/gemini-2.5-flash_perc.txt'
echo 'src/output/gemini-2.0-flash-lite'
cat 'src/output/gemini-2.0-flash-lite.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.0-flash-lite_relink.md' > 'src/output/gemini-2.0-flash-lite_relink.md' 2> 'src/output/gemini-2.0-flash-lite_perc.txt'
echo 'src/output/gemini-2.0-flash-001'
cat 'src/output/gemini-2.0-flash-001.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.0-flash-001_relink.md' > 'src/output/gemini-2.0-flash-001_relink.md' 2> 'src/output/gemini-2.0-flash-001_perc.txt'
echo 'src/output/gemini-2.0-flash'
cat 'src/output/gemini-2.0-flash.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.0-flash_relink.md' > 'src/output/gemini-2.0-flash_relink.md' 2> 'src/output/gemini-2.0-flash_perc.txt'
echo 'src/output/gemini-2.5-flash-preview-04-17'
cat 'src/output/gemini-2.5-flash-preview-04-17.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.5-flash-preview-04-17_relink.md' > 'src/output/gemini-2.5-flash-preview-04-17_relink.md' 2> 'src/output/gemini-2.5-flash-preview-04-17_perc.txt'
echo 'src/output/gemini-1.5-flash-8b'
cat 'src/output/gemini-1.5-flash-8b.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-1.5-flash-8b_relink.md' > 'src/output/gemini-1.5-flash-8b_relink.md' 2> 'src/output/gemini-1.5-flash-8b_perc.txt'
echo 'src/output/gemini-2.0-flash-lite-preview'
cat 'src/output/gemini-2.0-flash-lite-preview.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.0-flash-lite-preview_relink.md' > 'src/output/gemini-2.0-flash-lite-preview_relink.md' 2> 'src/output/gemini-2.0-flash-lite-preview_perc.txt'
echo 'src/output/gemini-2.0-flash-lite-001'
cat 'src/output/gemini-2.0-flash-lite-001.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.0-flash-lite-001_relink.md' > 'src/output/gemini-2.0-flash-lite-001_relink.md' 2> 'src/output/gemini-2.0-flash-lite-001_perc.txt'
echo 'src/output/gemini-1.5-flash-002'
cat 'src/output/gemini-1.5-flash-002.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-1.5-flash-002_relink.md' > 'src/output/gemini-1.5-flash-002_relink.md' 2> 'src/output/gemini-1.5-flash-002_perc.txt'
echo 'src/output/gemini-2.5-flash-lite-preview-06-17'
cat 'src/output/gemini-2.5-flash-lite-preview-06-17.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.5-flash-lite-preview-06-17_relink.md' > 'src/output/gemini-2.5-flash-lite-preview-06-17_relink.md' 2> 'src/output/gemini-2.5-flash-lite-preview-06-17_perc.txt'
echo 'src/output/gemini-2.0-flash-lite-preview-02-05'
cat 'src/output/gemini-2.0-flash-lite-preview-02-05.txt' | src/relink.py tmp/dedupe_idlinksrc.tsv 'src/output/gemini-2.0-flash-lite-preview-02-05_relink.md' > 'src/output/gemini-2.0-flash-lite-preview-02-05_relink.md' 2> 'src/output/gemini-2.0-flash-lite-preview-02-05_perc.txt'
